---
application:
  name: "nexusdeploy"
  project: "nexus-app"
  organization: "QoveryCommunity"
routers:
- name: "main-nexusdeploy"
  routes:
  - application_name: "nexusdeploy"
    paths:
    - "/*"
